[fmt]
line_length = 120
tab_width = 2
bracket_spacing = true
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first_multi'
sort_imports = true

[profile.default]
solc_version = '0.8.30'
libs = ['node_modules', 'lib']
optimizer_runs = 10_000
# Mappings for Libraries
remappings = [
  'forge-std/=node_modules/forge-std/src',
  'forge-std/=node_modules/@openzeppelin/contracts',
  'halmos-cheatcodes=node_modules/halmos-cheatcodes',
  'contracts/=src/contracts',
  'interfaces/=src/interfaces',
]

[profile.optimized]
via_ir = true
out = 'out-via-ir'

[profile.test]
via_ir = true
out = 'out-via-ir'

[profile.docs]
src = 'src/interfaces/'

[fuzz]
runs = 1000

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
sepolia = "${SEPOLIA_RPC}"
holesky = "${HOLESKY_RPC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
