apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  selector:
    # Selects pods with the matching labels to belong to this deployment.
    matchLabels:
      name: nginx
  replicas: 2
  template:
    metadata:
      # Labels for the pods where the containers will be running.
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
