apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    name: nginx
  ports:
    - protocol: TCP
      # New port that will be created to connect to the app.
      port: 8080
      # Port used by the container.
      targetPort: 80
      # Port to be exposed by the node between the range 3000-32767.
      nodePort: 30922
  type: NodePort
