apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  # Selects the pods to expose based on their labels. Should be the same as `spec.template.metadata.labels` in `deployment.yml` because that defines the labels for pods.
  selector:
    name: nginx
  ports:
    - protocol: TCP
      # New port that will be created to connect to the app. This is the port of the service.
      port: 8080
      # Port used by the container.
      targetPort: 80
      # Port to be exposed by the node between the range 3000-32767.
      nodePort: 30922
  type: NodePort
